using System.ComponentModel;
using System.ServiceProcess;
using System.Configuration.Install;  // Ensure this reference exists

namespace OSKLock
{
    [RunInstaller(true)]
    public partial class ProjectInstaller : Installer
    {
        public ProjectInstaller()
        {
            // This method initializes the components (this part might be autogenerated)
            InitializeComponent();

            // ServiceProcessInstaller defines the account under which the service runs
            ServiceProcessInstaller processInstaller = new ServiceProcessInstaller();
            processInstaller.Account = ServiceAccount.LocalSystem;  // Change to appropriate account if necessary

            // ServiceInstaller defines the properties of the service
            ServiceInstaller serviceInstaller = new ServiceInstaller();
            serviceInstaller.ServiceName = "OSKLockService";
            serviceInstaller.DisplayName = "OSK Lock Service";
            serviceInstaller.StartType = ServiceStartMode.Automatic;

            // Add the installers to the Installers collection
            Installers.Add(processInstaller);  // This refers to the Installers collection from the base Installer class
            Installers.Add(serviceInstaller);
        }
    }
}
